# CHAP 45- 프로미스

## 프로미스가 생겨난 배경

- JS는 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용한다. 하지만
- `콜백 헬로 인해 가독성이 나쁘`고 `비동기 처리중 발생한 에러 처리가 곤란`하며, 여러 개의 비동기 처리를 한 번에 처리하는데 한계가 있다.
- 이 점을 극복하기 위해 ES6에는 비동기 처리를 위한 또 다른 패턴으로 프로미스를 도입했다.
  - 프로미스에서는 then,catch,finally 후속 처리 메서드를 통해 콜백 헬을 해결한다.

## 비동기 처리를 위한 콜백 패턴의 단점

### 콜백 헬

- 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.
- 따라서 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.
- 이때 콜백함수를 전달하는 것이 일반적이며, 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수 & 비동기 처리가 실패하면 호출될 콜백 함수를 전달 할 수 있다.
  - ‼️콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 `콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상` 💥이 발생하는데, 이를 `콜백 헬`이라 한다.
- 콜백 헬은 가독성을 나쁘게 하며 실수를 유발하는 원인이 된다.

### 에러 처리의 한계

```jsx
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error("캐치한 에러", e);
}
```

- 예제에서 setTimeout의 콜백 함수가 실행될 때, setTimeout 함수는 이미 콜 스택에서 제거된 상태이다.
- 에러는 콜 스택의 아래 방향으로 전파된다. 위의 예제에서 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니기 때문에 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

## 프로미스의 생성

```jsx
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

- Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스를 생성한다.
- Promise 생성자 함수는 비동기 처리를 수행할 콜백함수를 인수로 전달받는데, 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.
- 비동기 처리기 성공하면 비동기 처리 결과를 resolve함수에 인수로 전달하면서 호출하고, 실패하면 에러를 reject 함수에 인수로 전달하면서 호출한다.
- 프로미스는 현재 비동기 처리가 어떻게 진행되고 있는지 나타내는 상태 정보를 갖는다.

| 프로미스의 상태 정보 | 의미                                  | 상태 변경 조건                   |
| -------------------- | ------------------------------------- | -------------------------------- |
| pending              | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled (settled)  | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected (settled)   | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

- 프로미스의 상태는 resolve/reject 함수를 호출하는 것으로 결정된다.
- 프로미스는 비동기 처리 결과도 상태로 갖는다.
  ```jsx
  // fulfilled된 프로미스
  const fulfilled = new Promise((resolve) => resolve(1));

  // rejected된 프로미스
  const rejected = new Promise((_, reject) =>
    reject(new Error("error occurred"))
  );
  ```
  ⇒ 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.

## 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백함수가 선택적으로 호출된다. 이때 `후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달`된다.
- `모든 후속 처리 메서드는 프로미스를 반환`하며, 비동기로 동작한다.

### Promise.prototype.then

```jsx
// fulfilled
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error("rejected"))).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // Error: rejected
```

- 첫번째 콜백 함수는 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수다
- 두번째 콜백 함수는 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수다

### Promise.prototype.catch

```jsx
// rejected
new Promise((_, reject) => reject(new Error("rejected"))).catch((e) =>
  console.log(e)
); // Error: rejected
```

- catch 메서드는 한 개의 콜백 함수를 인수로 전달 받는다.
- catch 메서드의 콜백함수는 프로미스가 rejected상태인 경우에만 호출된다.

### Promise.prototype.finally

- finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- finally 메서드의 콜백 함수는 프로미스의 성공 실패 와 상관없이 무조건 한 번 호출된다.

## 프로미스의 에러 처리

1. then 메서드의 두번째 콜백 함수로 처리할 수 있다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
  (res) => console.log(res),
  (err) => console.error(err)
); // Error: 404
```

1. 프로미스의 후속 처리 메서드 catch를 사용해 처리할 수도 있다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err)); // Error: 404
```

- `then메서드의 두번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못`하고 코드가 복잡해져서 가독성이 좋지 않다.
- `catch 메서드`는 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러와 then 메서드 내부에서 발생한 에러까지 `모두 캐치`할 수 있다.

💫  따라서 에러 처리를 catch 메서드에서 하는 것을 권장한다.

## 프로미스 체이닝

- then,catch,finally 후속 처리 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다. 이를 프로미스 체이닝이라고 한다.
- 이를 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백헬이 발생하지 않는다.
- 다만, 프로미스도 콜백 패턴을 사용하며, 콜백 패턴은 가독성이 좋지않다. ⇒ ES8에 도입된 async/await를 통해 해결 가능.

## 프로미스의 정적 메서드

### Promise.resolve/Promise.reject

```jsx
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]

// 에러 객체를 reject하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error("Error!"));
rejectedPromise.catch(console.log); // Error: Error!
```

- 각각 모두 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.

### Promise.all

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
  .catch(console.error);
```

- 여러 비동기 처리를 모두 병렬처리할 때 사용한다.
- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.
- **모든 프로미스가 모두 fulfilled 상태가 되면** 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다.
- Promise.all 메서드가 종료하는데 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 프로미스의 처리시간보다 조금 길다.
- 처리 순서가 보장된다.
- 하나라도 rejected 상태가 되면 나머지 즉시 종료한다.

### Promise.race

```jsx
Promise.race([
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 1")), 3000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 2")), 2000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 3")), 1000)
  ),
])
  .then(console.log)
  .catch(console.log); // Error: Error 3
```

- **가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과**를 resolve하는 새로운 프로미스를 반환한다.
- 하나라도 rejected 상태가 되면 나머지 즉시 종료한다.

### Promise.allSettled

```jsx
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error!")), 1000)
  ),
]).then(console.log);
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```

- 전달 받은 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환한다.

## 마이크로태스크 큐

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
// 2 -> 3 -> 1  순으로 출력된다.
```

- 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스큐에 저장된다.
- 태스크 큐 보다 우선순위가 높다. ⇒ 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에 대기하고 있는 함수를 가져와 실행한다.

## fetch

```jsx
fetch("https://jsonplaceholder.typicode.com/todos/1").then((response) =>
  console.log(response)
);
```

- HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API이다.
- 프로미스를 지원하며 대부분의 모던 브라우저에서 제공한다.
- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.
- fetch 함수가 반환하는 프로미스는 기본적으로 404, 500 와 같은 HTTP 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok상태를 false로 설정한 response 객체를 resolve한다.
  - `네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject` 한다.
  - 따라서 response 객체의 ok 값을 확인해서 명시적으로 에러 처리를 해야한다.
  - cf) axios는 모든 HTTP에러를 reject하는 프로미스를 반환한다.
