# CHAP 46 - async/await

## async/await

```jsx
const fetch = require("node-fetch");

async function fetchTodo() {
  const url = "https://jsonplaceholder.typicode.com/todos/1";

  const response = await fetch(url);
  const todo = await response.json();
  console.log(todo);
  // {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
}

fetchTodo();
```

- 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 구현 할 수 있는 async/await가 도입되었다.
- 프로미스 기반으로 동작한다.
- 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

### async 함수

```jsx
// async 함수 선언문
async function foo(n) {
  return n;
}
foo(1).then((v) => console.log(v)); // 1

// async 함수 표현식
const bar = async function (n) {
  return n;
};
bar(2).then((v) => console.log(v)); // 2

// async 화살표 함수
const baz = async (n) => n;
baz(3).then((v) => console.log(v)); // 3

// async 메서드
const obj = {
  async foo(n) {
    return n;
  },
};
obj.foo(4).then((v) => console.log(v)); // 4

// async 클래스 메서드
class MyClass {
  async bar(n) {
    return n;
  }
}
const myClass = new MyClass();
myClass.bar(5).then((v) => console.log(v)); // 5
```

- await 키워드는 반드시 async 함수 내부에서 사용해야 한다.
- async 키워드를 사용해 정의하며, 언제나 프로미스를 반환한다.
- async 함수는 암묵적으로 반환값을 resolve하는 프로미스를 반환한다.
- 클래스의 constructor메서드(인스턴스를 반환해야함)는 async 메서드(프로미스를 반환해야함)가 될 수 없다.

### await 키워드

```jsx
const fetch = require("node-fetch");

const getGithubUserName = async (id) => {
  const res = await fetch(`https://api.github.com/users/${id}`); // ①
  const { name } = await res.json(); // ②
  console.log(name); // Ungmo Lee
};

getGithubUserName("ungmo2");
```

- 프로미스가 settled 상태(비동기 처리가 수행된 상태)가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환한다.
- 반드시 프로미스 앞에서 사용해야한다.
- `프로미스가 settled 상태가 되면 프로미스가 resolve 한 처리 결과가 res 변수에 할당된다.`
- 다음 실행을 일시 중지시켰다가 프로미스가 settled 상태가 되면 다시 재개한다.

### 에러처리

```jsx
const fetch = require("node-fetch");

const foo = async () => {
  try {
    const wrongUrl = "https://wrong.url";

    const response = await fetch(wrongUrl);
    const data = await response.json();
    console.log(data);
  } catch (err) {
    console.error(err); // TypeError: Failed to fetch
  }
};

foo();
```

- try … catch문을 사용할 수 있다.
- 프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 호출자가 명확하다 → Catch문에서 에러를 잡을 수 있다.

```jsx
const fetch = require("node-fetch");

const foo = async () => {
  const wrongUrl = "https://wrong.url";

  const response = await fetch(wrongUrl);
  const data = await response.json();
  return data;
};

foo().then(console.log).catch(console.error); // TypeError: Failed to fetch
```

- async 함수 내에서 catch문을 사용해서 에러 처리를 하지 않으면 async 함수는 발생한 에러를 reject하는 프로미스를 반환한다. → async함수 호출 후, catch 후속 처리 메서드를 사용해서 에러 캐치 가능.
